Temporary fix until we fix this issue.
```
+ ./src/openocd --version
+ head -1
+ sed '-es/+dev-[0]\+/_/' -es/-/_/g '-es/.* 0\./0./' '-es/ .*//' -es/_dirty//
+ ./src/openocd --version
+ head -1
+ sed '-es/[^(]*(//' '-es/)//' -es/://g -es/-//g '-es/[0-9][0-9][0-9][0-9]$/_\0/'
+ TZ=UTC
+ date +%Y%m%d%H%M%S
Packaging openocd
INFO:conda_build.build:Packaging openocd
Packaging openocd-git-h31b6ad1_0
INFO:conda_build.build:Packaging openocd-git-h31b6ad1_0
Traceback (most recent call last):
  File "/home/tansell/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/build.py", line 1240, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/build.py", line 719, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/build.py", line 627, in post_process_files
    get_build_metadata(m)
  File "/home/tansell/conda/lib/python3.6/site-packages/conda_build/post.py", line 523, in get_build_metadata
    raise ValueError("support for __conda_version__ has been removed as of Conda-build 3.0."
ValueError: support for __conda_version__ has been removed as of Conda-build 3.0.Try Jinja templates instead: http://conda.pydata.org/docs/building/meta-yaml.html#templating-with-jinja
```